language: ruby
os: linux
rvm: 2.3.3
sudo: required
dist: trusty

script:
  - gem install rubocop
  - rubocop
  - ./install --force-curl
  - ./uninstall -f || true
  - sudo rm -rf /home/linuxbrew/.linuxbrew
  - ./install
  - /home/linuxbrew/.linuxbrew/bin/brew install ack
  - ./uninstall -f || true
