#!/bin/sh
set -eu

brew_prefix=/usr/local

if test -w $brew_prefix || sudo -v; then
	prefix=$brew_prefix/Homebrew/Library/Homebrew/vendor
	test -w $brew_prefix || sudo chown $USER: $brew_prefix
else
	prefix=~/.linuxbrew/Homebrew/Library/Homebrew/vendor
fi
version=2.0.0-p648

echo >&2 "==> Installing Ruby to $prefix"
mkdir -p $prefix
curl -L https://homebrew.bintray.com/bottles-portable/portable-ruby-$version.x86_64_linux.bottle.tar.gz \
	| tar -xz -C $prefix
echo >&2 '==> Installing successful'

export "PATH=$prefix/portable-ruby/$version/bin:$PATH"
echo >&2 "==> `which ruby`"
ruby --version 1>&2
echo >&2 "==> Add Ruby to your PATH by running:"
echo "PATH=$prefix/portable-ruby/$version/bin"':$PATH'
